prefix : <urn:vocab:kws:>
prefix kws: <urn:vocab:kws:>
prefix kwsg: <urn:graph:kws:>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix fn: <java:uff.ic.swlab.jena.sparql.function.>

#testar
delete {graph ?sol {?s ?p ?o}}
where {
  {
    select ?sol
    {
      {select ?sol {graph ?sol {} FILTER(regex(str(?sol),"urn:graph:kws:[0-9]{3}:sol"))}}
      graph ?sol {?s ?p []. ?s (!:_|^(!:_))* ?o. filter (isIRI(?o))}
    }
    group by ?sol
    having (count(min(str(?o))) > 1)
  }
};
======================================================================================================
delete {graph ?sol {?s ?p ?o}}
where {
  {
    select ?sol
    {
      {select ?sol {graph ?sol {} FILTER(regex(str(?sol),"urn:graph:kws:[0-9]{3}:sol"))}}
      graph ?sol {?s ?p []. ?s (!:_|^(!:_))* ?o. filter (isIRI(?o))}
    }
    group by ?sol
    having (count(min(str(?o))) > 1)
  }
};


delete {graph ?sol {?s ?p ?o}}
where {
            select ?sol
            {
                select ?sol ?s (min(?o) as ?o_)
                {
                    {select ?sol {graph ?sol {} FILTER(regex(str(?sol),"urn:graph:kws:[0-9]{3}:sol"))}}
                    graph ?sol {?s (!:_|^(!:_))* ?o. filter (isIRI(?o))}}
                }
                group by ?sol ?s
            }
            group by ?sol
            having (count(distinct ?o_) > 1)
};