#STEP 1.4: BUSCANDO AS PROPRIEDADES DAS SEEDS
PREFIX kws: <urn:vocab:kws:>
PREFIX kwsg: <urn:graph:kws:>

#buscando as propriedades que match
WITH kwsg:seeds
INSERT {?member kws:matchingPredicate ?property_match.}
WHERE{
    GRAPH kwsg:seeds {
        ?member kws:value ?value.
        SERVICE <%1$s> {
            ?member ?property_match ?value.
        }
    }
};
