
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
prefix : <urn:vocab:kws:>
prefix kws: <urn:vocab:kws:>
prefix kwsg: <urn:graph:kws:>
prefix time: <http://www.w3.org/2006/time#>

drop graph kwsg:new_seeds;
drop graph kwsg:subgraphs;
#drop graph kwsg:groups;
drop graph kwsg:groups2;

#inserir tempo no grafo default
insert data {
    <%1$squery> a kws:Information;
        kws:keywordQuery '%2$s';
        kws:duration [
            a time:Duration;
            time:numericDuration "%3$s"^^xsd:decimal;
            time:unityType time:unitSecond
        ].
};