#STEP 1.1: BUSCA DOS LITERAIS DAS SEMENTES ENCONTRADAS

PREFIX kwsg: <urn:graph:kws:>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX text: <http://jena.apache.org/text#>
PREFIX fn: <java:uff.ic.swlab.jena.sparql.function.>
PREFIX kws: <urn:vocab:kws:>



WITH kwsg:seeds
INSERT {?s kws:value ?literal}
WHERE
{
    {
        SELECT ?s (max(?score_) as ?score)
        WHERE {
            {
        		GRAPH kwsg:seeds{
                            ?bag rdfs:member ?s.
        		
       	 		}
            }
            {
              SERVICE <%1$s>{
                    GRAPH kwsg:indexed{
                        (?s ?score_ ?literal) text:query (kws:comment '%2$s' 1).
                    } 
      		  }
            }
        }
        GROUP BY ?s
    }
    {
        SELECT ?s ?literal
        WHERE {
            {
                GRAPH kwsg:seeds{
        			 ?bag rdfs:member ?s.
        		
       	 		}
            }
            {
        		SERVICE <%1$s>{
                            GRAPH kwsg:indexed{
                                (?s ?score ?literal) text:query (kws:comment '%2$s'). #lista de propriedades
                            }
      			}
            }
        }
    	
    }
}