PREFIX kw: <http://kwantu.net/kw/>
PREFIX urn: <http://fliqz.com/>
prefix kws: <urn:vocab:kws:>
prefix kwsg: <urn:graph:kws:>
prefix meta: <http://www.semwebtech.org/mondial/10/meta#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix text: <http://jena.apache.org/text#>
prefix fn: <java:uff.ic.swlab.jena.sparql.function.>
prefix quira: <http://www.quira.org/>
with kwsg:seeds
insert {?s kws:value ?literal}
WHERE
{
    {
        select ?s (max(?score_) as ?score)
        where {
            {
        		graph kwsg:seeds{
        			?bag rdfs:member ?s.
        		
       	 		}
            }
            {
        	   service <%1$s>{	
                (?s ?score_ ?literal) text:query (rdfs:label '%2$s' 1). #lista de propriedades
      		  }
            }
        }
        group by ?s
    }
    {# ?s ?score ?literal
        select ?s ?literal
        where {
            {
                graph kwsg:seeds{
        			 ?bag rdfs:member ?s.
        		
       	 		}
            }
            {
        		service <%1$s>{
                	(?s ?score ?literal) text:query (rdfs:label '%2$s'). #lista de propriedades
      			}
            }
        }
    	
    }
}