PREFIX kw: <http://kwantu.net/kw/>
prefix kws: <urn:vocab:kws:>
prefix kwsg: <urn:graph:kws:>
prefix meta: <http://www.semwebtech.org/mondial/10/meta#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix text: <http://jena.apache.org/text#>
prefix fn: <java:uff.ic.swlab.jena.sparql.function.>
prefix quira: <http://www.quira.org/>

SELECT  (fn:genQueryString('%1$s', ?allValues) as ?new_kws)
WHERE{
  {
    select  (group_concat(?value) as ?allValues) where { graph kwsg:seeds {[] kws:value ?value.}}
   
  } 
  # esse filtro não funciona. Filtrar quando receber o valor do select no codigo
  # filter (strlen(?new_kws) > 0)
}