#!/bin/bash
export JVM_ARGS=${JVM_ARGS:--Xmx14G}
export JENA_HOME=/Users/lapaesleme/local/etc/jena/apache-jena-3.10.0
export PATH=$PATH:$JENA_HOME/bin

cp /Users/lapaesleme/GitHub/KwS/src/main/scripts/IMDb/IMDb.ttl.old /Users/lapaesleme/local/etc/jena/apache-jena-fuseki-3.10.0/run/configuration/IMDb.ttl
/Users/lapaesleme/local/etc/jena/apache-jena-3.10.0/bin/tdb2.tdbcompact -v --loc /Users/lapaesleme/local/etc/jena/apache-jena-fuseki-3.10.0/run/databases/IMDb



