#!/bin/bash
export JVM_ARGS=${JVM_ARGS:--Xmx14G}
export JENA_HOME=/Users/lapaesleme/local/etc/jena/apache-jena-3.10.0
export PATH=$PATH:$JENA_HOME/bin

cp /Users/lapaesleme/GitHub/KwS/src/main/scripts/IMDb/IMDb.ttl.old /Users/lapaesleme/local/etc/jena/apache-jena-fuseki-3.10.0/run/configuration/IMDb.ttl
echo $(date):" loading /Users/lapaesleme/local/var/temp/dump/IMDb/backup_imdb.nq..."
/Users/lapaesleme/local/etc/jena/apache-jena-3.10.0/bin/tdb2.tdbloader -v --loader parallel --loc /Volumes/Data/Users/lapaesleme/local/etc/jena/apache-jena-fuseki-3.10.0/run/databases/IMDb /Volumes/Data/Users/lapaesleme/local/var/temp/dump/IMDb/backup_imdb.nq
echo $(date):" finished loading /Volumes/Data/Users/lapaesleme/local/var/temp/dump/IMDb/backup_imdb.nq"
