#!/bin/bash

sudo rsync -avz --delete -e "ssh -p 2222 -l lapaesleme" --rsync-path="rsync" lapaesleme@virtua.la.paes-leme.name:/Users/lapaesleme/local/var/db/tdb/2/run/databases/DBpedia/ /media/ssd1tb/home/casanova-pc/jena/jena-3.12/apache-jena-fuseki-3.12.0/run/databases/DBpedia
