prefix : <urn:vocab:kws:>
prefix kws: <urn:vocab:kws:>
prefix kwsg: <urn:graph:kws:>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix text: <http://jena.apache.org/text#>


select *
from kwsg:sol1
from named kwsg:temp
where {
  { select distinct ?e1 ?e2
    where {
      [] a rdf:Bag;
         rdfs:member ?e1;
         rdfs:member ?e2. filter (str(?e2)>str(?e1))
      filter (not exists {?e1 (!(rdf:type | rdfs:member) | ^(!(rdf:type | rdfs:member)))+ ?e2})
    }
  }
  {
    {graph ?g {?e1 ?p1 ?e2.}}
  	union {graph ?g {?e2 ?_p1 ?e1.}}
  }
}




##########################
# selecionar resultado 2 #
##########################


with kwsg:sol1
insert {
    ?bag a rdf:Bag;
        kws:score ?score;
        kws:size ?size;
        kws:comment ?comment1;
        rdfs:member ?m.
    ?m kws:comment ?comment2.}
using kwsg:temp3
using named kwsg:temp
where {
  {
    select ?bag (coalesce(?_score,0) as ?score) ?size
    where {
      ?bag a rdf:Bag.
      ?bag kws:size ?size
      optional {(?bag ?_score) text:query '%1$s'}.
    }
    order by desc(coalesce(?_score,0)) ?size
    limit 3
  }
  ?bag rdfs:member ?m; kws:comment ?comment1; kws:size ?size.
  {graph ?g {?m kws:comment ?comment2.}}
};






