prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix text: <http://jena.apache.org/text#>
prefix kws: <http://localhost:8080/kws/vocab/>
prefix kwsg: <urn:graph:kws:>

drop graph kwsg:seeds;
insert {graph kwsg:seeds {?bag a rdf:Bag; rdfs:member ?s.}}
where {
  {bind(bnode() as ?bag)}
  service <http://localhost:3030/Mondial/sparql> {
    graph kwsg:indexed {?s text:query '(states Brazil)'.}
  }
};