PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?label
WHERE  {
     graph ?sol{
  { <http://dbpedia.org/resource/Mountain_Time_Zone> rdfs:label ?label.} 
  	
  
  }
}
      
    

