prefix : <urn:vocab:kws:>
prefix kws: <urn:vocab:kws:>
prefix kwsg: <urn:graph:kws:>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>



drop graph kwsg:indexed;
insert {graph kwsg:indexed {?s kws:comment ?comment}}
where {
    select ?s (group_concat(?o) as ?comment)
    where {
        ?s ?p ?o.
        filter (isLiteral(?o) && !isNumeric(?o) && datatype(?o) not in (xsd:date,xsd:datetime))
    }
    group by ?s
};

