#!/bin/bash
export HOME=~
export SCRIPT_HOME="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"/IMDb
export DATA_HOME=/opt/local/var/db/tdb/2/run

sudo rsync -avz --exclude "run" --delete -e "ssh -i $HOME/swlab-srv1.pem" --rsync-path="sudo rsync" $SCRIPT_HOME/IMDb.ttl.new.aws  ec2-user@swlab-srv1.ddns.net:$DATA_HOME/configuration/IMDb2.ttl

ssh -i ~/swlab-srv1.pem ec2-user@swlab-srv1.ddns.net 'export JVM_ARGS=-Xmx120G ; export JENA_HOME=/opt/local/etc/jena/apache-jena-fuseki-3.13.1 ; export DATA_HOME=/opt/local/var/db/tdb/2/run ; export PATH=$PATH:$JENA_HOME/bin ; rm -R $DATA_HOME/lucene/IMDb2; java -cp $JENA_HOME/fuseki-server.jar jena.textindexer --desc=$DATA_HOME/configuration/IMDb2.ttl'