prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix text: <http://jena.apache.org/text#>
prefix imdb: <http://localhost:8080/resource/vocab/>
prefix rsc: <http://localhost:8080/resource/>
prefix kws: <http://localhost:8080/kws/vocab/>

insert {
  ?c a rdf:Seq;
     kws:score ?score;
     ?p1 ?m.
  ?m ?p2 ?o.
}
where {
  service <http://localhost:3030/Temp/sparql> {
    {
      select ?c (sum(coalesce(?sc,0)) as ?score)
      where {
        ?c a rdf:Seq; rdfs:member ?m.
        optional {?m kws:score ?sc}.
      }
      group By ?c
      limit 10
    }
    {?c a rdf:Seq; rdfs:member ?m. ?c ?p1 ?m.}
    optional {?m ?p2 ?o.}
  }
}



