#!/bin/bash
export HOME=/Users/lapaesleme
export SCRIPT_HOME=$HOME/GitHub/KwS/src/main/resources/scripts/DBpedia
export DATA_HOME=/opt/local/var/db/tdb/2/run

sudo rsync -avz --exclude "run" --delete -e "ssh -i $HOME/swlab-srv1.pem" --rsync-path="sudo rsync" $SCRIPT_HOME/DBpedia.ttl.new.aws  ec2-user@swlab-srv1.ddns.net:$DATA_HOME/configuration/DBpedia.ttl

ssh -i ~/swlab-srv1.pem ec2-user@swlab-srv1.ddns.net 'export JVM_ARGS=-Xmx120G ; export JENA_HOME=/opt/local/etc/jena/apache-jena-fuseki-3.13.1 ; export DATA_HOME=/opt/local/var/db/tdb/2/run ; export PATH=$PATH:$JENA_HOME/bin ; rm -R $DATA_HOME/lucene/DBpedia; java -cp $JENA_HOME/fuseki-server.jar jena.textindexer --desc=$DATA_HOME/configuration/DBpedia.ttl'