prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix text: <http://jena.apache.org/text#>
prefix imdb: <http://localhost:8080/resource/vocab/>
prefix rsc: <http://localhost:8080/resource/>
prefix kws: <http://localhost:8080/kws/vocab/>

insert {
  graph <urn:kws:seeds> {?bag a rdf:Bag; rdfs:member ?s.}
}
where {
  {select (bnode() as ?bag) where {}}
  service <http://localhost:3030/IMDb/sparql> {
    graph <urn:kws:indexed> {?s text:query ('%1$s' 10).}
  }
}