prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix text: <http://jena.apache.org/text#>
prefix imdb: <http://localhost:8080/resource/vocab/>
prefix kws: <http://localhost:8080/kws/vocab/>
prefix rsc: <http://localhost:8080/resource/>

construct {
  ?a rdfs:label ?lbla.
  ?b rdfs:label ?lblb.
  ?a kws:score ?sca2.
  ?b kws:score ?scb2.
  ?s1 rdfs:label ?lbls1.
  ?s2 rdfs:label ?lbls2.
  [] a rdf:Seq;
    rdf:_1 ?a;
    rdf:_2 ?p1;
    rdf:_2 ?_p1;
    rdf:_3 ?s1;
    rdf:_4 ?p2;
    rdf:_4 ?_p2;
    rdf:_5 ?s2;
    rdf:_6 ?p3;
    rdf:_6 ?_p3;
    rdf:_7 ?b.
  ?a ?p1 ?s1. ?s1 ?p2 ?s2. ?s2 ?p3 ?b.
  ?a ?p1 ?s1. ?s1 ?p2 ?s2. ?b ?_p3 ?s2.
  ?a ?p1 ?s1. ?s2 ?_p2 ?s1. ?s2 ?p3 ?b.
  ?a ?p1 ?s1. ?s2 ?_p2 ?s1. ?b ?_p3 ?s2.
  ?s1 ?_p1 ?a. ?s1 ?p2 ?s2. ?s2 ?p3 ?b.
  ?s1 ?_p1 ?a. ?s1 ?p2 ?s2. ?b ?_p3 ?s2.
  ?s1 ?_p1 ?a. ?s2 ?_p2 ?s1. ?s2 ?p3 ?b.
  ?s1 ?_p1 ?a. ?s2 ?_p2 ?s1. ?b ?_p3 ?s2.
}
where {
  {select ?a ?b ?sca2 ?scb2
    where {
      {select ?a (sum(?sca) as ?sca2)
        where {{{SELECT (imdb:profession as ?pred) where {}}
            union {SELECT (imdb:originalTitle as ?pred) where {}}
            union {SELECT (imdb:primaryTitle as ?pred) where {}}
            union {SELECT (imdb:titleType as ?pred) where {}}
			union {SELECT (imdb:genre as ?pred) where {}}
			union {SELECT (imdb:job as ?pred) where {}}
			union {SELECT (imdb:primaryName as ?pred) where {}}
			union {SELECT (imdb:primaryProfession as ?pred) where {}}
			union {SELECT (imdb:region as ?pred) where {}}
			union {SELECT (imdb:types as ?pred) where {}}
			union {SELECT (imdb:language as ?pred) where {}}
  			union {SELECT (imdb:attributes as ?pred) where {}}}
          	{(?a ?sca) text:query (?pred "(actress out of africa Meryl Streep)").}}
		group by ?a
		order by desc(sum(?sca))
		limit 50
      }

      {select ?b (sum(?scb) as ?scb2)
        where {{{SELECT (imdb:profession as ?pred) where {}}
            union {SELECT (imdb:originalTitle as ?pred) where {}}
			union {SELECT (imdb:primaryTitle as ?pred) where {}}
			union {SELECT (imdb:titleType as ?pred) where {}}
			union {SELECT (imdb:genre as ?pred) where {}}
			union {SELECT (imdb:job as ?pred) where {}}
			union {SELECT (imdb:primaryName as ?pred) where {}}
			union {SELECT (imdb:primaryProfession as ?pred) where {}}
			union {SELECT (imdb:region as ?pred) where {}}
			union {SELECT (imdb:types as ?pred) where {}}
			union {SELECT (imdb:language as ?pred) where {}}
  			union {SELECT (imdb:attributes as ?pred) where {}}}
          	{(?b ?scb) text:query (?pred "(actress out of africa Meryl Streep)").}}
		group by ?b
		order by desc(sum(?scb))
		limit 50
      }
      filter (str(?a) > str(?b)).
    }
  }
  {{?a ?p1 ?s1. ?s2 ?p3 ?b. ?s1 ?p2 ?s2.
    	filter ((?p1 != rdf:type) && (?p2 != rdf:type) && (?p3 != rdf:type))}
    union {?a ?p1 ?s1. ?b ?_p3 ?s2. ?s2 ?p []. ?s1 ?p2 ?s2.
	    filter ((?p1 != rdf:type) && (?p2 != rdf:type) && (?_p3 != rdf:type))}
    union {?a ?p1 ?s1. ?s1 ?p []. ?s2 ?p3 ?b. ?s2 ?_p2 ?s1.
    	filter ((?p1 != rdf:type) && (?_p2 != rdf:type) && (?p3 != rdf:type))}
    union {?a ?p1 ?s1. ?s1 ?p []. ?b ?_p3 ?s2. ?s2 ?_p2 ?s1.
    	filter ((?p1 != rdf:type) && (?_p2 != rdf:type) && (?_p3 != rdf:type))}
    union {?s1 ?_p1 ?a. ?s2 ?p3 ?b. ?s1 ?p2 ?s2.
    	filter ((?_p1 != rdf:type) && (?p2 != rdf:type) && (?p3 != rdf:type))}
    union {?s1 ?_p1 ?a. ?b ?_p3 ?s2. ?s2 ?p []. ?s1 ?p2 ?s2.
    	filter ((?_p1 != rdf:type) && (?p2 != rdf:type) && (?_p3 != rdf:type))}
    union {?s1 ?_p1 ?a. ?s2 ?p3 ?b. ?s2 ?_p2 ?s1.
    	filter ((?_p1 != rdf:type) && (?_p2 != rdf:type) && (?p3 != rdf:type))}
    union {?s1 ?_p1 ?a. ?b ?_p3 ?s2. ?s2 ?_p2 ?s1.
    	filter ((?_p1 != rdf:type) && (?_p2 != rdf:type) && (?_p3 != rdf:type))}
  }
  OPTIONAL {?a rdfs:label ?lbla.}
  OPTIONAL {?b rdfs:label ?lblb.}
  OPTIONAL {?s1 rdfs:label ?lbls1.}
  OPTIONAL {?s2 rdfs:label ?lbls2.}
}


