prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix text: <http://jena.apache.org/text#>
prefix imdb: <http://localhost:8080/resource/vocab/>
prefix rsc: <http://localhost:8080/resource/>
prefix kws: <http://localhost:8080/kws/vocab/>

construct {
  ?seq kws:score ?score.
  ?seq a rdf:Seq.
  ?seq ?p1 ?e.
  ?e ?p2 ?o.
  ?s ?_p2 ?e.
}
where{
  {select ?seq ((coalesce(?sca,0) + coalesce(?sc1,0) + coalesce(?sc2,0) + coalesce(?scb,0)) as ?score)
    where {
      ?seq a rdf:Seq; rdf:_1 ?a; rdf:_3 ?s1; rdf:_5 ?s2; rdf:_7 ?b.
      optional {?a kws:score ?sca.}
      optional {?s1 kws:score ?scs1.}
      optional {?s2 kws:score ?scs2.}
      optional {?b kws:score ?scb.}
    }
    order by desc(coalesce(?sca,0) + coalesce(?sc1,0) + coalesce(?sc2,0) + coalesce(?scb,0))
    limit 30
  }
  {?seq ?p1 ?e.
      optional {?e ?p2 ?o.}
      optional {?s ?_p2 ?e.}
      filter (!(?_p1 in (rdf:_1,rdf:_2,rdf:_3,rdf:_4,rdf:_5,rdf:_6,rdf:_7,rdf:_8) && ?s != ?seq))
  }
}