prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix text: <http://jena.apache.org/text#>
prefix imdb: <http://localhost:8080/resource/vocab/>
prefix rsc: <http://localhost:8080/resource/>
prefix kws: <http://localhost:8080/kws/vocab/>

construct {?e kws:score ?score.}
where {
    select ?e (sum(?sc) as ?score)
    where {
        {
            select distinct ?e
            where {
                {[] rdf:_3 ?e.}
                union {[] rdf:_5 ?e.}
                union {[] rdf:_7 ?e.}
                union {[] rdf:_9 ?e.}
                union {[] rdf:_11 ?e.}
            }
        }
  	{
            {SELECT (imdb:profession as ?pred) where {}}
            union {SELECT (imdb:originalTitle as ?pred) where {}}
            union {SELECT (imdb:primaryTitle as ?pred) where {}}
            union {SELECT (imdb:titleType as ?pred) where {}}
            union {SELECT (imdb:genre as ?pred) where {}}
            union {SELECT (imdb:job as ?pred) where {}}
            union {SELECT (imdb:primaryName as ?pred) where {}}
            union {SELECT (imdb:primaryProfession as ?pred) where {}}
            union {SELECT (imdb:region as ?pred) where {}}
            union {SELECT (imdb:types as ?pred) where {}}
            union {SELECT (imdb:language as ?pred) where {}}
            union {SELECT (imdb:attributes as ?pred) where {}}
  	}
  	service <http://localhost:3030/IMDb/sparql> {
            (?e ?sc) text:query (?pred "(actress \"out of africa\"^3 Meryl Streep)").
  	}
    }
    group by ?e
}

