prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix text: <http://jena.apache.org/text#>
prefix imdb: <http://localhost:8080/resource/vocab/>
prefix rsc: <http://localhost:8080/resource/>
prefix kws: <http://localhost:8080/kws/vocab/>

insert {
  ?container kws:score ?score.
  ?member ?p ?o.
}
where {
  service <http://localhost:3030/Temp/sparql> {
    {
      select ?container (avg(coalesce(?sc,0)) as ?score)
      where {
        ?container a rdf:Seq; rdfs:member ?m.
        optional {?m kws:score ?sc}.
      }
      group By ?container
      #order by desc(avg(coalesce(?sc,0)))
      limit 10
    }
    ?container a rdf:Seq; rdfs:member ?member.
    optional {?member ?p ?o.}
  }
}

