prefix kws: <urn:vocab:kws:>
prefix kwsg: <urn:graph:kws:>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix meta: <http://www.semwebtech.org/mondial/10/meta#>
prefix text: <http://jena.apache.org/text#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

select ?pos (avg(?recall) as ?avg)
where{
  {
    #select ?q
    #where {?q a kws:Ranking; kws:entry [kws:position ?pos].}
    #group by ?q
    #having (max(?pos)>10)
    select ?q
    where {
      values ?seq {"036"}
      ?q a kws:Ranking. filter(contains(str(?q),?seq))
    }
  }
  ?q a kws:Ranking; kws:entry [kws:position ?pos; kws:recall ?recall]
}
group by ?pos
order by ?pos
limit 10