prefix : <urn:vocab:kws:>
prefix kws: <urn:vocab:kws:>
prefix kwsg: <urn:graph:kws:>
prefix meta: <http://www.semwebtech.org/mondial/10/meta#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix text: <http://jena.apache.org/text#>
prefix fn: <java:uff.ic.swlab.jena.sparql.function.>

#####################################################################
# calculando os caminhos com distância 4
#####################################################################

# distancia 4
insert {
    graph ?sol {?e1 ?p1 ?e2. ?e2 ?p2 ?e3. ?e3 ?p3 ?e4. ?e4 ?p4 ?e5.}
    graph ?sol {?e1 ?p1 ?e2. ?e2 ?p2 ?e3. ?e3 ?p3 ?e4. ?e5 ?_p4 ?e4.}
    graph ?sol {?e1 ?p1 ?e2. ?e2 ?p2 ?e3. ?e4 ?_p3 ?e3. ?e4 ?p4 ?e5.}
    graph ?sol {?e1 ?p1 ?e2. ?e2 ?p2 ?e3. ?e4 ?_p3 ?e3. ?e5 ?_p4 ?e4.}
    graph ?sol {?e1 ?p1 ?e2. ?e3 ?_p2 ?e2. ?e3 ?p3 ?e4. ?e4 ?p4 ?e5.}
    graph ?sol {?e1 ?p1 ?e2. ?e3 ?_p2 ?e2. ?e3 ?p3 ?e4. ?e5 ?_p4 ?e4.}
    graph ?sol {?e1 ?p1 ?e2. ?e3 ?_p2 ?e2. ?e4 ?_p3 ?e3. ?e4 ?p4 ?e5.}
    graph ?sol {?e1 ?p1 ?e2. ?e3 ?_p2 ?e2. ?e4 ?_p3 ?e3. ?e5 ?_p4 ?e4.}
    graph ?sol {?e2 ?_p1 ?e1. ?e2 ?p2 ?e3. ?e3 ?p3 ?e4. ?e4 ?p4 ?e5.}
    graph ?sol {?e2 ?_p1 ?e1. ?e2 ?p2 ?e3. ?e3 ?p3 ?e4. ?e5 ?_p4 ?e4.}
    graph ?sol {?e2 ?_p1 ?e1. ?e2 ?p2 ?e3. ?e4 ?_p3 ?e3. ?e4 ?p4 ?e5.}
    graph ?sol {?e2 ?_p1 ?e1. ?e2 ?p2 ?e3. ?e4 ?_p3 ?e3. ?e5 ?_p4 ?e4.}
    graph ?sol {?e2 ?_p1 ?e1. ?e3 ?_p2 ?e2. ?e3 ?p3 ?e4. ?e4 ?p4 ?e5.}
    graph ?sol {?e2 ?_p1 ?e1. ?e3 ?_p2 ?e2. ?e3 ?p3 ?e4. ?e5 ?_p4 ?e4.}
    graph ?sol {?e2 ?_p1 ?e1. ?e3 ?_p2 ?e2. ?e4 ?_p3 ?e3. ?e4 ?p4 ?e5.}
    graph ?sol {?e2 ?_p1 ?e1. ?e3 ?_p2 ?e2. ?e4 ?_p3 ?e3. ?e5 ?_p4 ?e4.}
    graph kwsg:groups2 {?sol rdfs:member ?e2.}
    graph kwsg:groups2 {?sol rdfs:member ?e3.}
    graph kwsg:groups2 {?sol rdfs:member ?e4.}
}
where {
    #graph kwsg:pairs {?seq a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5; kws:solution ?sol.}
    {
      service <%1$s>  {
        {
        	{
          		{
            		{
              			{
      						{select distinct ?e1 ?e5 WHERE {service <%2$s> 													{graph kwsg:pairs {[] a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5.}}}}
            #service <%1$s>  {
                			?e1 ?p1 ?e2. filter(?e2 not in (?e1) && !fn:schema(?p1))
              			}
                	    ?e2 ?p2 ?e3. filter(?e3 not in (?e1,?e2) && !fn:schema(?p2))
            		 }
                	  ?e3 ?p3 ?e4. filter(?e4 not in (?e1,?e2,?e3) && !fn:schema(?p3))
          		 }
                 ?e4 ?p4 ?e5. filter(?e4 not in (?e1,?e2,?e3,?e4) && !fn:schema(?p4))
        	}
            #}
        }
        union {
        		{
          			{
            			{
              				{
          			
      						{select distinct ?e1 ?e5 WHERE {service <%2$s> 													{graph kwsg:pairs {[] a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5.}}}}
            #service <%1$s>  {
               				 	?e1 ?p1 ?e2. filter(?e2 not in (?e1) && !fn:schema(?p1)) #1
              				 }
                			 ?e2 ?p2 ?e3. filter(?e3 not in (?e1,?e2) && !fn:schema(?p2)) #2
            			}
                		?e3 ?p3 ?e4. filter(isIRI(?e4) && ?e4 not in (?e1,?e2,?e3) && !fn:schema(?p3)) #3
          			}
                	?e5 ?_p4 ?e4. filter(?e4 not in (?e1,?e2,?e3,?e4) && !fn:schema(?_p4)) #4
        		}
            #}
        }
        union {
        		{
          			{
            			{
              				{
      						{select distinct ?e1 ?e5 WHERE {service <%2$s> 													{graph kwsg:pairs {[] a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5.}}}}
            #service <%1$s>  {
                			?e1 ?p1 ?e2. filter(?e2 not in (?e1) && !fn:schema(?p1)) #1
              				}
                			?e2 ?p2 ?e3. filter(isIRI(?e3) && ?e3 not in (?e1,?e2) && !fn:schema(?p2)) #2
            			}
                		?e4 ?_p3 ?e3. filter(?e4 not in (?e1,?e2,?e3) && !fn:schema(?_p3)) #3
          			}
                	?e4 ?p4 ?e5. filter(?e4 not in (?e1,?e2,?e3,?e4) && !fn:schema(?p4)) #4
        		}
            #}
        }
        union {
        		{
          			{
            			{
              				{
      						{select distinct ?e1 ?e5 WHERE {service <%2$s> 													{graph kwsg:pairs {[] a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5.}}}}
            #service <%1$s>  {
                			?e1 ?p1 ?e2. filter(?e2 not in (?e1) && !fn:schema(?p1)) #1
              				}
                		    ?e2 ?p2 ?e3. filter(isIRI(?e3) && ?e3 not in (?e1,?e2) && !fn:schema(?p2)) #2
            			}
                		?e4 ?_p3 ?e3. filter(?e4 not in (?e1,?e2,?e3) && !fn:schema(?_p3)) #3
          			}
                	?e5 ?_p4 ?e4. filter(?e4 not in (?e1,?e2,?e3,?e4) && !fn:schema(?_p4)) #4
        		}
            #}
        }
        union {
        		{
          			{
            			{
              				{
      						{select distinct ?e1 ?e5 WHERE {service <%2$s> 													{graph kwsg:pairs {[] a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5.}}}}
            #service <%1$s>  {
                			?e1 ?p1 ?e2. filter(isIRI(?e2) && ?e2 not in (?e1) && !fn:schema(?p1)) #1
              				}
                			?e3 ?_p2 ?e2. filter(?e3 not in (?e1,?e2) && !fn:schema(?_p2)) #2
            			}
                		?e3 ?p3 ?e4. filter(?e4 not in (?e1,?e2,?e3) && !fn:schema(?p3)) #3
          		  }
                  ?e4 ?p4 ?e5. filter(?e4 not in (?e1,?e2,?e3,?e4) && !fn:schema(?p4)) #4
        	}
            #}
        }
        union {
        		{
          			{
            			{
              				{
      						{select distinct ?e1 ?e5 WHERE {service <%2$s> 													{graph kwsg:pairs {[] a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5.}}}}
            #service <%1$s>  {
                			?e1 ?p1 ?e2. filter(isIRI(?e2) && ?e2 not in (?e1) && !fn:schema(?p1)) #1
              				}
                			?e3 ?_p2 ?e2. filter(?e3 not in (?e1,?e2) && !fn:schema(?_p2)) #2
            			}
                		?e3 ?p3 ?e4. filter(isIRI(?e4) && ?e4 not in (?e1,?e2,?e3) && !fn:schema(?p3)) #3
          			}
                	?e5 ?_p4 ?e4. filter(?e4 not in (?e1,?e2,?e3,?e4) && !fn:schema(?_p4)) #4
        		}
            #}
        }
        union {
        		{
          			{
            			{
              				{
      						{select distinct ?e1 ?e5 WHERE {service <%2$s> 													{graph kwsg:pairs {[] a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5.}}}}
            #service <%1$s>  {
                			?e1 ?p1 ?e2. filter (isIRI(?e2) && ?e2 not in (?e1) && !fn:schema(?p1)) #1
              				}
                			?e3 ?_p2 ?e2. filter (?e3 not in (?e1,?e2) && !fn:schema(?_p2)) #2
            			}
                		?e4 ?_p3 ?e3. filter(?e4 not in (?e1,?e2,?e3) && !fn:schema(?_p3)) #3
          			}
                	?e4 ?p4 ?e5. filter(?e4 not in (?e1,?e2,?e3,?e4) && !fn:schema(?p4)) #4
        		}
            #}
        }
        union {
        		{
          			{
            			{
              				{
      						{select distinct ?e1 ?e5 WHERE {service <%2$s> 													{graph kwsg:pairs {[] a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5.}}}}
            #service <%1$s>  {
                			?e1 ?p1 ?e2. filter (isIRI(?e2) && ?e2 not in (?e1) && !fn:schema(?p1)) #1
              				}
                			?e3 ?_p2 ?e2. filter (?e3 not in (?e1,?e2) && !fn:schema(?_p2)) #2
            			}
                		?e4 ?_p3 ?e3. filter(?e4 not in (?e1,?e2,?e3) && !fn:schema(?_p3)) #3
          			}
                	?e5 ?_p4 ?e4. filter(?e4 not in (?e1,?e2,?e3,?e4) && !fn:schema(?_p4)) #4
        		}
            #}
        }
        union {
        		{
          			{
            			{
              				{
      						{select distinct ?e1 ?e5 WHERE {service <%2$s> 													{graph kwsg:pairs {[] a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5.}}}}
            #service <%1$s>  {
                			?e2 ?_p1 ?e1. filter (?e2 not in (?e1) && !fn:schema(?_p1)) #1
              				}
                			?e2 ?p2 ?e3. filter (?e3 not in (?e1,?e2) && !fn:schema(?p2)) #2
            			}
                		?e3 ?p3 ?e4. filter(?e4 not in (?e1,?e2,?e3) && !fn:schema(?p3)) #3
          			}
                	?e4 ?p4 ?e5. filter(?e4 not in (?e1,?e2,?e3,?e4) && !fn:schema(?p4)) #4
        	}
            #}
        }
        union {
        		{
          			{
            			{
              				{
      						{select distinct ?e1 ?e5 WHERE {service <%2$s> 													{graph kwsg:pairs {[] a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5.}}}}
            #service <%1$s>  {
                			?e2 ?_p1 ?e1. filter (?e2 not in (?e1) && !fn:schema(?_p1)) #1
              				}
                			?e2 ?p2 ?e3. filter (?e3 not in (?e1,?e2) && !fn:schema(?p2)) #2
            			}
                		?e3 ?p3 ?e4. filter(isIRI(?e4) && ?e4 not in (?e1,?e2,?e3) && !fn:schema(?p3)) #3
          			}
                	?e5 ?_p4 ?e4. filter(?e4 not in (?e1,?e2,?e3,?e4) && !fn:schema(?_p4)) #4
        		}
            #}
        }
        union {
        		{
          			{
            			{
              				{
      						{select distinct ?e1 ?e5 WHERE {service <%2$s> 													{graph kwsg:pairs {[] a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5.}}}}
            #service <%1$s>  {
                			?e2 ?_p1 ?e1. filter (?e2 not in (?e1) && !fn:schema(?_p1)) #1
              				}
                			?e2 ?p2 ?e3. filter (isIRI(?e3) && ?e3 not in (?e1,?e2) && !fn:schema(?p2)) #2
            			}	
                		?e4 ?_p3 ?e3. filter(?e4 not in (?e1,?e2,?e3) && !fn:schema(?_p3)) #3
          			}
                  	?e4 ?p4 ?e5. filter(?e4 not in (?e1,?e2,?e3,?e4) && !fn:schema(?p4)) #4
        		}
            #}
        }
        union {
        		{
          			{
            			{
              				{
      						{select distinct ?e1 ?e5 WHERE {service <%2$s> 													{graph kwsg:pairs {[] a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5.}}}}
            #service <%1$s>  {
               		 		?e2 ?_p1 ?e1. filter (?e2 not in (?e1) && !fn:schema(?_p1)) #1
              				}
                			?e2 ?p2 ?e3. filter (isIRI(?e3) && ?e3 not in (?e1,?e2) && !fn:schema(?p2)) #2
            			}
                		?e4 ?_p3 ?e3. filter(?e4 not in (?e1,?e2,?e3) && !fn:schema(?_p3)) #3
          			}
                	?e5 ?_p4 ?e4. filter(?e4 not in (?e1,?e2,?e3,?e4) && !fn:schema(?_p4)) #4
        	}
            #}
        }
        union {
        		{
          			{
            			{
              				{
      						{select distinct ?e1 ?e5 WHERE {service <%2$s> 													{graph kwsg:pairs {[] a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5.}}}}
            #service <%1$s> {
                			?e2 ?_p1 ?e1. filter (?e2 not in (?e1) && !fn:schema(?_p1)) #1
              				}
                			?e3 ?_p2 ?e2. filter (?e3 not in (?e1,?e2) && !fn:schema(?_p2)) #2
            			}
                		?e3 ?p3 ?e4. filter(?e4 not in (?e1,?e2,?e3) && !fn:schema(?p3)) #3
          			}
                	?e4 ?p4 ?e5. filter(?e4 not in (?e1,?e2,?e3,?e4) && !fn:schema(?p4)) #4
        		}
            #}
        }
        union {
        		{
          			{
            			{
              				{
      						{select distinct ?e1 ?e5 WHERE {service <%2$s> 													{graph kwsg:pairs {[] a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5.}}}}
            #service <%1$s>  {
                			?e2 ?_p1 ?e1. filter (?e2 not in (?e1) && !fn:schema(?_p1)) #1
              				}
                			?e3 ?_p2 ?e2. filter (?e3 not in (?e1,?e2) && !fn:schema(?_p2)) #2
            			}
                		?e3 ?p3 ?e4. filter(isIRI(?e4) && ?e4 not in (?e1,?e2,?e3) && !fn:schema(?p3)) #3
          			}
                	?e5 ?_p4 ?e4. filter(?e4 not in (?e1,?e2,?e3,?e4) && !fn:schema(?_p4)) #4
        		}
            #}
        }
        union {
        		{
          			{
            			{
              				{
      						{select distinct ?e1 ?e5 WHERE {service <%2$s> 													{graph kwsg:pairs {[] a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5.}}}}
            #service <%1$s>  {
                			?e2 ?_p1 ?e1. filter (?e2 not in (?e1) && !fn:schema(?_p1)) #1
              				}
               		 		?e3 ?_p2 ?e2. filter (?e3 not in (?e1,?e2) && !fn:schema(?_p2)) #2
            			}
                		?e4 ?_p3 ?e3. filter(?e4 not in (?e1,?e2,?e3) && !fn:schema(?_p3)) #3
          			}
                	?e4 ?p4 ?e5. filter(?e4 not in (?e1,?e2,?e3,?e4) && !fn:schema(?p4)) #4
        		}
            #}
        }
        union {
        		{
          			{
            			{
              				{
      						{select distinct ?e1 ?e5 WHERE {service <%2$s> 													{graph kwsg:pairs {[] a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5.}}}}
            #service <%1$s>  {
                			?e2 ?_p1 ?e1. filter (?e2 not in (?e1) && !fn:schema(?_p1)) #1
              				}
                			?e3 ?_p2 ?e2. filter (?e3 not in (?e1,?e2) && !fn:schema(?_p2)) #2
            			}
                		?e4 ?_p3 ?e3. filter(?e4 not in (?e1,?e2,?e3) && !fn:schema(?_p3)) #3
          			}
                	?e5 ?_p4 ?e4. filter(?e4 not in (?e1,?e2,?e3,?e4) && !fn:schema(?_p4)) #4
        		}
            #}
        }
    }
  }
  	{graph kwsg:pairs {[] a rdf:Seq; rdf:_1 ?e1; rdf:_2 ?e5; kws:solution ?sol.}}
};

drop graph kwsg:pairs;