prefix kws: <urn:vocab:kws:>
prefix kwsg: <urn:graph:kws:>
prefix meta: <http://www.semwebtech.org/mondial/10/meta#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix text: <http://jena.apache.org/text#>
prefix fn: <java:uff.ic.swlab.jena.sparql.function.>
PREFIX agg: <http://uff.ic.swlab.jena.sparql.aggregate/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>



##########################################################
#Calcular frequênciaScore e armazenar em cada solução
##########################################################

insert {graph ?g {?sol kws:frequencyScore ?freqScore.}}
WHERE {
        
	SELECT ?g ?sol (agg:kwFreqScore('%1$s', ?kwscomment) as ?freqScore)
	WHERE {
            graph ?g {
                ?sol a rdf:Bag; rdfs:member ?s.
                ?s kws:comment ?kwscomment.
                FILTER(isLiteral(?kwscomment) && !regex(str(?s),'urn:graph:kws:[0-9]{3}:sol'))
            }
            FILTER(regex(str(?g),'urn:graph:kws:groups'))
        }
        group by ?g ?sol
};