prefix : <urn:vocab:kws:>
prefix kws: <urn:vocab:kws:>
prefix kwsg: <urn:graph:kws:>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix meta: <http://www.semwebtech.org/mondial/10/meta#>
prefix text: <http://jena.apache.org/text#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>



##################################################
# trazer kws:comment do Mondial para as soluções #
##################################################.

insert {graph ?g {?s ?dtProp ?literal; rdfs:label ?lbl.}}
where {
  graph ?g {
    {{?s ?p []} union {[] ?p ?s}}
    optional {
      service <%1$s> {
        {?s ?dtProp ?literal. filter(isLiteral(?literal))}
      }
    }
    optional {
      service <%1$s> {
        {graph kwsg:labels {?s rdfs:label ?lbl}}
      }
    }
  }
};




